name: Update Surge Geo Rules

on:
  schedule:
    - cron: '0 3 * * *'
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install pandas requests

      - name: Download IPInfo Lite CSV
        env:
          IPINFO_TOKEN: ${{ secrets.IPINFO_TOKEN }}
        run: |
          curl -L "https://ipinfo.io/data/free/country_asn.csv.gz?token=${IPINFO_TOKEN}" -o test1.gz
          echo "country_asn.csv.gz 内容："
          cat test1.gz || true
          curl -L "https://ipinfo.io/data/free/lite.csv.gz?token=${IPINFO_TOKEN}" -o test2.gz
          echo "lite.csv.gz 内容："
          cat test2.gz || true
          curl -v "https://ipinfo.io/data/free/?token=${IPINFO_TOKEN}" 2>&1 | head -50


      - name: Run extraction script
        run: python extract.py
